### ISSUE TITLE
Update running-config without restarting?

### ISSUE THREAD

**Issue by brentonannan** [bitwalker/conform_exrm#1]
Is there a way to generate a new `running-config` if I make updates to my `RELEASE_CONFIG_FILE`?

My current setup is somewhat manual, however I'm planning on building a system around hot upgrades, wherein the config for a given server can be updated dynamically, and would like to rebuild the `running-config` dynamically when this happens, without having to stop and start my application.

Is this currently possible? Also, if it were, would these changes be taken up by a running application? (I think they wouldn't - is it possible to reload them dynamically?)

**Comment by bitwalker** [comment]
Changes to running-config only get applied during application upgrades/downgrades or restarts. You could manually write some code which would read in the configuration from running-config and apply it, using `Application.put_env`, then call it using `./bin/yourapp rpc <module> <function> <args>`, but there is no built in way to do this currently.

**Comment by brentonannan** [comment]
Hey @bitwalker sorry to necropost here, but I just wanted to check something: If I update my `config/my_application.schema.exs` and `config/my_application.conf` to include new configuration, will the conform script run during a hot upgrade/downgrade, making my new settings available in the newly running code?

**Comment by bitwalker** [comment]
@brentonannan Yes it will :)

**Comment by brentonannan** [comment]
Awesome, I figured it would, just didn't see it specifically mentioned anywhere! So a workaround for what I was asking here would be to do a release with just the patchlevel of the version bumped; that'd work, right?

**Comment by bitwalker** [comment]
Yep exactly!

**Comment by brentonannan** [comment]
:+1: Thanks a lot!

**Comment by brentonannan** [comment]
@bitwalker back again!

It seems that `RELEASE_CONFIG_FILE` isn't respected when used with `upgrade` - `app/running-config/app.conf` gets replaced with the `app.conf` provided with the release (which is all empty strings for me because secrets).

Any advice on how to overcome this? Or am I just doing something wrong?

**Comment by bitwalker** [comment]
Yeah it should be respecting that environment variable, could you open another issue on the exrm repo referencing this one and close this one out? I'll get that fixed ASAP

**Comment by brentonannan** [comment]
Jeez, sorry mate, I completely forgot about this response; will do that now. Cheers.
