### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alco** [bitwalker/conform_exrm#3]
Hi. Could you please consider publishing a new release to Hex that includes [this commit](https://github.com/bitwalker/conform_exrm/commit/6445fb707fd8c78a274449292addc359a8df422e)? For some reason we can't get conform to be included in the release when using the latest published `conform_exrm`.

**Comment by bitwalker** [comment]
Done! (0.3.0 for reference)

**Comment by tverlaan** [comment]
For me this commit is causing conform not to be included. Which version of exrm and conform should I use? I've tried exrm 1.0.1, conform 1.0.0-rc8 and conform_exrm 0.3.0 but that didn't work.
Right now I'm sticking with exrm 1.0.0-rc7, conform 1.0.0-rc7 and conform_exrm 0.2.0 which does work for me.

**Comment by bitwalker** [comment]
@tverlaan I'm using conform 2.0, conform_exrm 1.0, and exrm 1.0 with no problems.
